language: rust
script:
  - cargo test --verbose --all
deploy:
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: cargo publish --token $PUBLISH_TOKEN
    on:
      tags: true
      branch: master
